name: Crypto Trading Bot

on:
  schedule:
    - cron: '0 */4 * * *'  # every 4 hours
    
  workflow_dispatch:  # manual trigger

jobs:
  run-crypto-bot:
    runs-on: ubuntu-latest
    env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance --upgrade
          pip install -r requirements.txt

      - name: Run crypto bot
        run: python crypto_bot.py